

name: Node.js Controlador

on:
  push:
    branches:
      -main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Instalacion de dependecias
        run: npm install


