 name: Controlador de JS
 
 on:
  push:
    branches:
      -main
 jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/es-check-action@1.0.2
        with:
          directory: 'dist'
          ecmaVersion: 'es5'
          files: '*.js'
      - name: Instalacion de dependecias
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        
          
