name: Controlador JS

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:
  
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/es-check-action@1.0.2
        with:
          directory: 'dist'
          ecmaVersion: 'es5'
          files: '*.js'
  
        
          
